---

- name: Init client instance
  hosts: client
  become: yes
  tasks:
    - name: Install k6 yum repository
      yum:
        name: https://dl.k6.io/rpm/repo.rpm
        disable_gpg_check: yes
        state: present

    - name: Install k6
      yum:
        name:
          - k6
          - gcc
        state: present
        update_cache: yes


# https://github.com/JoeDog/siege/
    - name: Download siege
      ansible.builtin.unarchive:
        src: http://download.joedog.org/siege/siege-latest.tar.gz
        dest: /home/ec2-user
        remote_src: yes

    - name: Compile and install siege
      ansible.builtin.shell: |
        cd /home/ec2-user/siege-*
        ./configure
        make
        sudo make install